<<<<<<< HEAD
name: prefeitura_app
description: Aplicativo da prefeitura para agendamentos e serviços
version: 1.0.0

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
dependencies:
  image_picker: ^1.0.4
  firebase_storage: ^11.0.16

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
=======
name: prefeitura_app
description: Aplicativo da prefeitura para agendamentos e serviços
version: 1.0.0

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
dependencies:
  image_picker: ^1.0.4
  firebase_storage: ^11.0.16

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
>>>>>>> 0249e0ebaf4372c031fc4162c30d7b9e490bbdfa
